version: '3.7'

services:
  nest:
    container_name: 'nest'
    build: .
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 27182:27182
    command: npm run start:debug
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: 'nest_mongo'
    volumes:
      - mongodb_data_container:/data/db
    env_file:
      - .env
    environment:
      MONGODB_USER: root
      MONGODB_DATABASE: db
      MONGODB_PASS: '1234'
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
networks:
  webnet:
volumes:
  mongodb_data_container: